# docker/compose.override-ports.yml
#
# 笏笏 蛟句挨縺ｫ 窶懊％縺ｮ繧ｵ繝ｼ繝薙せ縺縺代・繝ｼ繝医ｒ髢九″縺溘＞窶・蝣ｴ髱｢逕ｨ縲・
#    萓具ｼ壹せ繝・・繧ｸ繝ｳ繧ｰ迺ｰ蠅・〒 Grafana 縺縺醍｢ｺ隱阪＠縺溘＞縲√↑縺ｩ縲・

services:
  grafana: { ports: [ "3000:3000" ] }
  # 縺ｻ縺九↓髢九¢縺溘＞繧ゅ・縺後≠繧後・霑ｽ險・
